### PR TITLE
Repair pipeline

### PR DESCRIPTION
**Pull request by tbody-cfs**
The pipelines are currently failing due to a missing import of `_version`.

Replace the __version__ variable with one from importlib.metadata

### CODE REVIEW

**Comment by tbody-cfs** [comment]
Actually, this seems to be due to a failing install of HDF5

**Comment by tbody-cfs** [comment]
```
running build_ext
         Loading library to get build settings and version: libhdf5.so
         error: Unable to load dependency HDF5, make sure HDF5 is installed properly
         error: libhdf5.so: cannot open shared object file: No such file or directory
         [end of output]
   
     note: This error originates from a subprocess, and is likely not a problem with pip.
     ERROR: Failed building wheel for h5py
   ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects
```

**Comment by tbody-cfs** [comment]
I'll look at how to get HDF5 working. Could we add a conda install in the actions?

**Comment by tbody-cfs** [comment]
It works! A big thanks to @istevenson-cfs for helping to figure this out!

**Comment by bendudson** [comment]
Awesome! Thanks, and nice work @tbody-cfs and @istevenson-cfs !

**Review by bendudson — APPROVED** [review]

**Pull request merged**
